export const POST_USER_DATA = 'POST_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';

// audio data types
export const CREATE_BASE_AUDIO_CONTEXT_AND_ANALYSER = 'CREATE_BASE_AUDIO_CONTEXT_AND_ANALYSER';
export const CREATE_AUDIO_DATA = 'CREATE_AUDIO_DATA';
export const PLAY_PAUSE_SOUND_FROM_FILE = 'PLAY_PAUSE_SOUND_FROM_FILE';
export const CREATE_STREAME_DATA = 'CREATE_STREAME_DATA';
export const START_MUTE_STREAME_AUDIO = 'START_MUTE_STREAME_AUDIO';
export const MERGE_CANVAS_WIDTH = 'MERGE_CANVAS_WIDTH';

// blocks data types
export const SET_VISIBILITY = 'SET_VISIBILITY';

// Presets data types
export const SET_ROCK_PRESET = 'SET_ROCK_PRESET';
export const SET_JAZZ_PRESET = 'SET_JAZZ_PRESET';
export const SET_RAP_PRESET = 'SET_RAP_PRESET';
