export const POST_USER_DATA = 'POST_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';

//audio data types
export const CREATE_AUDIO_DATA = 'CREATE_AUDIO_DATA';
export const PLAY_PAUSE_SOUND_FROM_FILE = 'PLAY_PAUSE_SOUND_FROM_FILE';
export const CREATE_STREAME_DATA = 'CREATE_STREAME_DATA';
export const START_MUTE_STREAME_AUDIO = 'START_MUTE_STREAME_AUDIO';
export const MERGE_CANVAS_WIDTH = 'MERGE_CANVAS_WIDTH'
